flowchart TB
    CatalogContext[Catalog Context]
    InventoryContext[Inventory Context]
    OrderContext[Order Context]
    CustomerContext[Customer Context]
    AuthenticationContext[Authentication Context]

    CatalogContext --> InventoryContext
    InventoryContext --> OrderContext
    OrderContext --> CustomerContext
    AuthenticationContext --> OrderContext
